### ISSUE TITLE
[BUG] Settings not saved

### ISSUE THREAD

**Issue by Mara-Li** [Oliver-Akins/file-hider#2]
**Describe the bug**
When reloading or re-opening Obsidian after set a hidden file/folder, the folder reappear in the explorer.
`data.json` of the folder doesn't exist either, meaning that settings are not saved. 

**To Reproduce**
<!-- Steps to reproduce the behavior:
1. Go to hide folder/files
2. Reload obsidian

**Comment by Oliver-Akins** [comment]
If you could provide some extra info that would be great:

  - Operating System and Version:
  - Obsidian Version:

This will help to ensure that it isn't a platform-dependant bug

**Comment by Mara-Li** [comment]
It was on windows 11 ! 
I also try on IOS, and same things : no settings and folder saved, no data.json.

**Comment by Oliver-Akins** [comment]
Thanks for the information!

I'll work on a fix to get it working properly tonight, since saving the settings is a pretty important part of it. lol

**Comment by Oliver-Akins** [comment]
@Mara-Li This has been fixed, it will be coming in the 1.0.1 update (there's another bug that I found which I want to fix before releasing it)

**Comment by rajagidh** [comment]
Hi - I am still having the same problem i.e. reloading the Obsidian program unhides the previously hidden folder. I am using it on Linux Mint. I can see the data.json file with the correct data setting but for some reason reloading the Obsidian does not keep the folder hidden. Could you please help? Thank you!

**Comment by wasd-xyz** [comment]
Hello. Faced with the same problem of saving WIn11 settings in obsidian version 1.8.4, can I expect a fix? This plugin is very important.

**Comment by Mara-Li** [comment]
I created my own plugin following the issue in this plugin so…
